language: cpp

compiler:
  - gcc
  - clang

before_script:
  - wget https://cmake.org/files/v3.15/cmake-3.15.5.tar.gz
  - tar -xzvf cmake-3.15.5.tar.gz
  - rm -f cmake-3.15.5.tar.gz
  - (cd cmake-3.15.5 && ./bootstrap && make -j4 && sudo make install)
  - rm -rf cmake-3.15.5
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update
  - sudo apt-get install gcc-9 g++-9 --yes
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - cmake -version
  - mkdir build
  - (cd build && cmake.. )

script:
  - (cd build && make)
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/ctest --output-on-failure)