language: cpp

before_script:
  - ./install_requirements.sh
  - cmake -version
  - g++ -v
  - gcc -v
  - mkdir build
  - (cd build && cmake .. )

script:
  - (cd build && make -j 6)
  - (cd build && ctest --output-on-failure)