language: cpp

dist: bionic

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update
  - sudo apt-get install gcc-9 g++-9 --yes
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
  - tar xvf cmake-3.15.5-Linux-x86_64.tar.gz
  - ./cmake-3.15.5-Linux-x86_64/bin/cmake -version
  - g++ -v
  - gcc -v
  - mkdir build
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/cmake .. )

script:
  - (cd build && make -j 6)
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/ctest --output-on-failure)