language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - gcc
      - g++
      - clang
      - cmake


before_script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
  - tar xvf cmake-3.15.5-Linux-x86_64.tar.gz
  - mkdir build
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/cmake .. )

script:
  - (cd build && make)
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/ctest --output-on-failure)