language: cpp

dist: bionic

script:
  - ./install_requirements.sh
  - (cd build && ../cmake .. )
  - (cd build && make -j 4)
  - (cd build && ../cmake-3.15.5-Linux-x86_64/bin/ctest --output-on-failure)